### ISSUE TITLE
Video rotations are change automaticlly

### ISSUE THREAD

**Issue by HoangDuoc** [zevarito/PodRTC#1]
When I perform the operation removeRender and addRender to change video display at different views then rotations of video are change automatically.
Please explain to me why?? And how do i resolve it ?? Many thanks !!

**Comment by zevarito** [comment]
@HoangDuoc this library is compiled as it comes from WebRTC codebase, please report any issues you might find in their bug tracker here[0].

I am totally open to hear suggestions about which revisions should be build with this Pod.

You might want to try the latest update of the Pod which is (56.17541.0.0), notice that it might not be available in the Cocoapod website yet but you can try it linking the Pod with this git repository.

[0] https://bugs.chromium.org/p/webrtc/issues/list
